name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - 'release/v1.0.0'  # Update this line with your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract Version Number
      id: extract_version
      run: echo ::set-output name=VERSION::${{ github.ref_name }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./src/Demo.Pipeline.Backend
        file: ./src/Demo.Pipeline.Backend/DemoPipeline.Api/Dockerfile
        tags: <span class="math-inline">\{\{ secrets\.ACR\_LOGIN\_SERVER \}\}/your\-image\-name\:</span>{{ steps.extract_version.outputs.VERSION }}
        push: true