name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - 'release/v1.0.0'  # Update this line with your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./src/Demo.Pipeline.Backend
        file: ./src/Demo.Pipeline.Backend/DemoPipeline.Api/Dockerfile
        push: true