name: Trigger auto deployment for demo-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ release/v1.0.0 ]
    paths:
    - 'src/Demo.Pipeline.Backend/DemoPipeline.Api/**'
    - '.github/workflows/demo-container-app-AutoDeployTrigger-6271fdbc-5b72-4a2f-939f-a3c3272fcc60.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/Demo.Pipeline.Backend/DemoPipeline.Api 
          registryUrl: pipelinedemo2.azurecr.io
          registryUsername: ${{ secrets.DEMOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: demo-container-app
          resourceGroup: demo-pipeline
          imageToBuild: pipelinedemo2.azurecr.io/demo-container-app:${{ github.sha }}
          
            

     

