name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - release/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/Demo.Pipeline.Backend
          file: ./src/Demo.Pipeline.Backend/DemoPipeline.Api/Dockerfile
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/pipelinedemo2:${{ github.sha }}
          push: true

  create-container-app:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Create Azure Container App (if it doesn't exist)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp create \
              --resource-group my-resource-group \
              --name my-container-app \
              --image ${{ secrets.ACR_LOGIN_SERVER }}/pipelinedemo2:${{ github.sha }} \
            
              - name: Update Azure Container App (if it already exists)
                uses: azure/CLI@v1
                with:
                  azcliversion: <desired_version>
                  inlineScript: |
                    az containerapp update \
                      --resource-group demo-pipeline \
                      --name test-demo-container \
                      --image ${{ secrets.ACR_LOGIN_SERVER }}/pipelinedemo2:${{ github.sha }}